### ISSUE TITLE
Job Postings by Sector for Ireland?

### ISSUE THREAD

**Issue by soliverc** [hiring-lab/data#40]
Hello

I am reading the Readme and it says that "Each folder contains the following files: **job_postings_by_sector_{country_code}.csv** and **aggregate_job_postings_{country_code}.csv**

The IE folder does not contain job postings by sector. Looks like it's the only country that doesn't have this information. 

I wonder could you supply me with this data? Is it possible to get this data from 2019 also? 

Thank you

**Comment by allisonshrivastava** [comment]
Hi @soliverc apologies for the delay in my reply. We don't currently supply sector level data for the Irish market but should that change I'll be sure to let you know.

All the best,

Allison
